### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by ahnmur** [jayanam/jbake-tools#11]
Hi there! Thanks so much for the amazing tool!
I've used it successfully a couple of times, but now I'm getting the following error:

```

Traceback (most recent call last):
  File "C:\Users\Anna\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\jbake-tools-main\jb_operators.py", line 86, in execute
    bpy.ops.object.mode_set(mode='OBJECT')
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: <unknown location>:-1

```

**Comment by ahnmur** [comment]
Ahh sorry, I noticed that GestampfteMaus had a similar issue. I tried creating a new file from scratch so I could share it with you, but now it seems to be working.
